version: "3.9"
services:
  app:
    image: rubyapp
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_HOST: db
    ports:
      - 3000:3000
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - appointment-data:/var/lib/postgresql/data
volumes:
  appointment-data:
    driver: local
    