version: "3.9"
services:
  app:
    image: elsonotake/rubyapp:1.2
    environment:
      database: <%= ENV['DATABASE_NAME'] %>
      username: <%= ENV['DATABASE_USERNAME'] %>
      password: <%= ENV['DATABASE_PASSWORD'] %>
      host: <%= ENV['DATABASE_HOST'] %>
      port: <%= ENV['DATABASE_PORT'] %>
    ports:
      - 3000:3000
