apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  elephant-database: aWZrbWpxYm4=
  elephant-username: aWZrbWpxYm4=
  elephant-password: NEJycHZkcmJVMFFadll3WmJ3MEgyUThldVJPakxIYno=
